# ============================================================================
# TechVortex'26 - PSEUDO-LABEL training on real Indian drone data (Kaggle T4)
# Trains a multi-task U-Net (extent + boundary) on tiles whose labels were
# generated by Delineate Anything v2 (knowledge distillation / self-training).
# Dataset: dharshapersonal/techvortex-pseudo-tiles (pseudo.zip of *.npz).
# Saves /kaggle/working/bund_unet_india.pth
# ============================================================================
import subprocess, sys
def _pip(*p): subprocess.run([sys.executable, "-m", "pip", "install", "-q", *p], check=False)
_pip("segmentation-models-pytorch")

import os, glob, zipfile, random, numpy as np, torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import segmentation_models_pytorch as smp

random.seed(0); np.random.seed(0); torch.manual_seed(0)
DEV = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEV, torch.cuda.get_device_name(0) if DEV == "cuda" else "")

SRC = "/kaggle/input/techvortex-pseudo-tiles/pseudo.zip"
WORK = "/kaggle/temp/pseudo"; os.makedirs(WORK, exist_ok=True)
with zipfile.ZipFile(SRC) as z:
    z.extractall(WORK)
files = sorted(glob.glob(WORK + "/*.npz")); random.shuffle(files)
print("pseudo-labeled tiles:", len(files))
nval = max(1, int(len(files) * 0.15))
val_f, tr_f = files[:nval], files[nval:]
print("train/val:", len(tr_f), len(val_f))


class DS(Dataset):
    def __init__(self, ff): self.ff = ff
    def __len__(self): return len(self.ff)
    def __getitem__(self, i):
        d = np.load(self.ff[i])
        img = (d["img"].astype("float32") / 255.0).transpose(2, 0, 1)
        y = np.stack([d["ext"].astype("float32"), d["bnd"].astype("float32")], 0)
        return torch.from_numpy(img), torch.from_numpy(y)


tl = DataLoader(DS(tr_f), batch_size=8, shuffle=True, num_workers=2, drop_last=True)
vl = DataLoader(DS(val_f), batch_size=8, shuffle=False, num_workers=2)

model = smp.Unet("resnet34", encoder_weights="imagenet", in_channels=3, classes=2).to(DEV)
opt = torch.optim.AdamW(model.parameters(), lr=3e-4)
dice = smp.losses.DiceLoss(mode="multilabel"); bce = nn.BCEWithLogitsLoss()
scaler = torch.cuda.amp.GradScaler()


def iou_ch(logits, y, ch):
    p = (torch.sigmoid(logits[:, ch]) > 0.5).float(); t = y[:, ch]
    inter = (p * t).sum((1, 2)); union = ((p + t) > 0).float().sum((1, 2))
    return ((inter + 1e-6) / (union + 1e-6)).mean().item()


EPOCHS, best = 25, 0.0
for ep in range(EPOCHS):
    model.train()
    for x, y in tl:
        x, y = x.to(DEV), y.to(DEV)
        opt.zero_grad()
        with torch.cuda.amp.autocast():
            out = model(x); loss = bce(out, y) + dice(out, y)
        scaler.scale(loss).backward(); scaler.step(opt); scaler.update()
    model.eval(); ei, bi = [], []
    with torch.no_grad():
        for x, y in vl:
            x, y = x.to(DEV), y.to(DEV)
            with torch.cuda.amp.autocast(): out = model(x)
            ei.append(iou_ch(out, y, 0)); bi.append(iou_ch(out, y, 1))
    me, mb = float(np.mean(ei)), float(np.mean(bi))
    print(f"epoch {ep+1}/{EPOCHS}  extent IoU = {me:.3f}   boundary IoU = {mb:.3f}")
    if me + mb > best:
        best = me + mb
        torch.save(model.state_dict(), "/kaggle/working/bund_unet_india.pth")
print("BEST extent+boundary:", round(best, 3))
print("Saved -> /kaggle/working/bund_unet_india.pth")
